services:
  proxy:
    build: 
      context: ./nginx
      dockerfile: Dockerfile.prod
    container_name: proxy
    tty: true
    networks:
      - nodenet
    ports:
      - "8080:80"
    depends_on:
      - app

  app:
    build: 
      context: ./node
      dockerfile: Dockerfile.prod
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 60s docker-entrypoint.sh
    command: node index.js
    networks:
      - nodenet
    volumes:
      - ./node:/usr/src/app 
    tty: true
    depends_on:
      - db

  db:
    image: mysql:5.7
    command: --innodb_use_native_aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - nodenet

networks:
  nodenet:
    driver: bridge
